// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNN2slvgt_RQ6lQx8K_oANw1xWGaVN9LM',
    appId: '1:561244051862:android:e8dd597b1c51155d8c65b7',
    messagingSenderId: '561244051862',
    projectId: 'date-7d307',
    storageBucket: 'date-7d307.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAJRd45Ac7LfPBKc8HBzcKQKaN2yhp3o8',
    appId: '1:561244051862:ios:22269754c776cc028c65b7',
    messagingSenderId: '561244051862',
    projectId: 'date-7d307',
    storageBucket: 'date-7d307.firebasestorage.app',
    iosBundleId: 'com.example.luvvy',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgF5ISpCDKherCjpz5zAEQAlNzl8G5DJE',
    appId: '1:561244051862:web:d2c9c1bc783907138c65b7',
    messagingSenderId: '561244051862',
    projectId: 'date-7d307',
    authDomain: 'date-7d307.firebaseapp.com',
    storageBucket: 'date-7d307.firebasestorage.app',
  );

}