// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEyzdJ45QX51exTqmGIGAkS_QWL-aoMUg',
    appId: '1:16790831811:android:4af20d33c14855dd2e1876',
    messagingSenderId: '16790831811',
    projectId: 'lovedate-c3e8b',
    storageBucket: 'lovedate-c3e8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD5XF_dAE-RGCtOIO4rxuj6LI7YmtuQso',
    appId: '1:16790831811:ios:e4ba112c325434a02e1876',
    messagingSenderId: '16790831811',
    projectId: 'lovedate-c3e8b',
    storageBucket: 'lovedate-c3e8b.firebasestorage.app',
    iosBundleId: 'com.example.luvvy',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVQZfMNPo-09n59EC1sxABWtOULqP2fhU',
    appId: '1:16790831811:web:6c8c2071c2120c212e1876',
    messagingSenderId: '16790831811',
    projectId: 'lovedate-c3e8b',
    authDomain: 'lovedate-c3e8b.firebaseapp.com',
    storageBucket: 'lovedate-c3e8b.firebasestorage.app',
  );

}